### Ping
GET http://localhost:8090/api/ping

### GET Account-Groups
GET http://localhost:8090/api/accountgroups/5d2577e6-8da3-4337-8e08-cb9136a2503e

### GET Alert-Rules
GET http://localhost:8090/api/alertrules/5d2577e6-8da3-4337-8e08-cb9136a2503e

### Submit Form
POST http://localhost:8090/submit
Content-Type: application/x-www-form-urlencoded

userInput=5d2577e6-8da3-4337-8e08-cb9136a2503e&ag=2089499&radioDirection=LR&radioDefault=classic